### ISSUE TITLE
How should PCBWay handle vias in pads?

### ISSUE THREAD

**Issue by jwiede** [bkw777/WP-2_IC_Card#1]
Brian,

Sent the design to PCBWay only to have them call-out the vias hiding in the pads, and ask whether those should be tented, filled, or what?  WHat is your expected handling for the vias-in-pads on the 015 design of the MRAM 512K?

As you mention having PCBway do them, and even have the designs over on PCBway (where I originally got it from, not stated there either that I or they could find), having explicit details on what options to use, etc. when ordering and how to handle things that will get asked (such as the vias-in-pads question) would definitely help the process.

Thanks!

**Comment by bkw777** [comment]
You don't do anything about them. No changes to the soldermask. If a via is in a pad, it just gets soldered along with the pad. They never asked me about that before and I've had a ton of these made while going through different versions. Though never assembly, just the pcbs.

If you're trying to get them populated not just the pcbs, then wait a day and I'll add a branch that has all the vias moved out of pads and add fiducials. For machine/paste soldering, the paste only provides a fixed amount of solder, and vias in pads robs some, leaving the joint light. It's no problem for hand soldering though.

**Comment by bkw777** [comment]
I've updated both the SRAM 128K and the MRAM 512K boards to move all the vias out of the pads, added fiducials, added manufacturer part numbers to the schematic, exported bom and centroid files.

The latest release gerbers include all the updates and exported files, and the pcbway page is updated.

**Comment by jwiede** [comment]
Brian, thanks so much, I really appreciate all the additional info.

-John W.


________________________________
